In [1]:
#https://www.kesci.com/mw/project/5dd236a800b0b900365eca9b
#本练习取之上述连接
import math

In [2]:
#实现sigmoid函数
def basic_sigmoid(x):
    s=1/(1+math.exp(-x))
    return s

In [3]:
basic_sigmoid(3)

0.9525741268224334

In [4]:
x=[1,2,3]
basic_sigmoid(x)

TypeError: bad operand type for unary -: 'list'

In [2]:
import numpy as np
x=np.array([1,2,3])
#print(math.exp(x))
print(np.exp(x))

[ 2.71828183  7.3890561  20.08553692]


In [3]:
x=np.array([1,2.4])
print(x+3)

[4.  5.4]


In [4]:
def basic_sigmoid_np(x):
    s=1/(1+np.exp(-x))
    return s

In [5]:
x=[1,2,3]#<=不是numpy类型引起的
basic_sigmoid_np(x)

TypeError: bad operand type for unary -: 'list'

In [6]:
x=np.array([1,2,3])#<=不是numpy类型引起的
basic_sigmoid_np(x)

array([0.73105858, 0.88079708, 0.95257413])

In [7]:
#Sigmoid gradient sigmoid的梯度下降
def sigmoid_derivative(x):
    s=1/(1+np.exp(-x))
    ds=s*(1-s)
    return ds

In [8]:
sigmoid_derivative(x)

array([0.19661193, 0.10499359, 0.04517666])

# 重塑数组
numpy np.shape和np.reshape()。
-X.shape用于获取矩阵/向量X的shape（维度）。
-X.reshape（...）用于将X重塑为其他尺寸。

例如，在计算机科学中，图像由shape为
的3D数组表示。但是，当你读取图像作为算法的输入时，会将其转换为维度为
的向量。换句话说，将3D阵列“展开”或重塑为1D向量。

In [9]:
#实现v = v.reshape((v.shape[0]*v.shape[1], v.shape[2])) 
def image2vector(image):
    v = image.reshape(image.shape[0]*image.shape[1]*image.shape[2],1)
    return v

In [10]:
#3*3*2
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])


In [11]:
print(image)
print(image.shape)
print(image.shape[0])
print(image.shape[1])
print(image.shape[2])

[[[0.67826139 0.29380381]
  [0.90714982 0.52835647]
  [0.4215251  0.45017551]]

 [[0.92814219 0.96677647]
  [0.85304703 0.52351845]
  [0.19981397 0.27417313]]

 [[0.60659855 0.00533165]
  [0.10820313 0.49978937]
  [0.34144279 0.94630077]]]
(3, 3, 2)
3
3
2


In [12]:
print(image2vector(image))

[[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.60659855]
 [0.00533165]
 [0.10820313]
 [0.49978937]
 [0.34144279]
 [0.94630077]]


# 行标准化
我们在机器学习和深度学习中使用的另一种常见技术是对数据进行标准化。 由于归一化后梯度下降的收敛速度更快，通常会表现出更好的效果。 通过归一化，也就是将x更改为
（将x的每个行向量除以其范数）

In [13]:
def normalizeRows(x):
    x_norm=np.linalg.norm(x,axis=1,keepdims=True)
    print(x_norm.shape)
    x=x/x_norm
    print(x.shape)
    return x

In [14]:
x = np.array([
    [0, 3, 4],
    [1, 6, 4]])
print(normalizeRows(x))

(2, 1)
(2, 3)
[[0.         0.6        0.8       ]
 [0.13736056 0.82416338 0.54944226]]


# 在normalizeRows（）中，你可以尝试print查看 x_norm和x的维度，然后重新运行练习cell。 你会发现它们具有不同的w维度。 鉴于x_norm采用x的每一行的范数，这是正常的。 因此，x_norm具有相同的行数，但只有1列。 那么，当你将x除以x_norm时，它是如何工作的？ 这就是所谓的广播broadcasting，我们现在将讨论它！

In [15]:
def softmax(x):
    x_exp=np.exp(x)
    x_sum=np.sum(x_exp,axis=1,keepdims=True)
    s=x_exp/x_sum
    return s

In [16]:
x = np.array([
    [9, 2, 5, 0, 0],
    [7, 5, 0, 0 ,0]])
print("softmax(x) = " + str(softmax(x)))

softmax(x) = [[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]


# 向量化
在深度学习中，通常需要处理非常大的数据集。 因此，非计算最佳函数可能会成为算法中的巨大瓶颈，并可能使模型运行一段时间。 为了确保代码的高效计算，我们将使用向量化。 例如，尝试区分点/外部/元素乘积之间的区别。

In [27]:
#W = np.random.rand(3,len(x1))
#print(W)
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]
x3=np.array([1,2,3])
x4=np.array([1,2,3]).reshape(3,1)
print(x4)
dot = np.dot(x3,x4)#元素相乘之和
dot1=np.outer(x1,x2)
mul = np.multiply(x1,x2)
#dot2 = np.dot(W,x1)
print(dot,dot1,mul)

[[1]
 [2]
 [3]]
[14] [[81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [63 14 14 63  0 63 14 35  0  0 63 14 35  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]] [81  4 10  0  0 63 10  0  0  0 81  4 25  0  0]


# 注意 不同于np.multiply()和* 操作符（相当于Matlab / Octave中的 .*）执行逐元素的乘法，np.dot()执行的是矩阵-矩阵或矩阵向量乘法，

# 实现L1和L2损失函数

In [65]:
def L1(yhat, y):
    """
    Arguments:
    yhat -- vector of size m (predicted labels)
    y -- vector of size m (true labels)
    
    Returns:
    loss -- the value of the L1 loss function defined above
    """
    
    ### START CODE HERE ### (≈ 1 line of code)
    loss = np.sum(np.abs(y - yhat))
    ### END CODE HERE ###
    
    return loss

In [66]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L1 = " + str(L1(yhat,y)))

L1 = 1.1


In [67]:
def L2(yhat, y):
    """
    Arguments:
    yhat -- vector of size m (predicted labels)
    y -- vector of size m (true labels)
    
    Returns:
    loss -- the value of the L2 loss function defined above
    """
    
    ### START CODE HERE ### (≈ 1 line of code)
    loss = np.dot((y - yhat),(y - yhat).T)
    ### END CODE HERE ###
    
    return loss

In [68]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L2 = " + str(L2(yhat,y)))

L2 = 0.43


你需要记住的内容：
-向量化在深度学习中非常重要， 它保证了计算的效率和清晰度。
-了解L1和L2损失函数。
-掌握诸多numpy函数，例如np.sum，np.dot，np.multiply，np.maximum等。