In [1]:
import numpy as np
from tensorflow import keras
import pandas as pd
from tensorflow.keras import layers
from sklearn import preprocessing

In [3]:
#round_price_data1.csv是经过处理后的周围房屋房价，取了16个周围房价，取16个是为了好卷积
data = pd.read_csv('round_price_data1.csv')
# Model / data parameters
num_classes = 10
input_shape = (28, 28, 1)

In [4]:
print(data) 

      price_real           0           1             2             3  \
0      1790000.0   1790000.0   1790000.0  1.790000e+06  1.790000e+06   
1      3080000.0   3080000.0   3080000.0  3.080000e+06  3.080000e+06   
2      4100000.0   4100000.0   4700000.0  4.800000e+06  4.800000e+06   
3      7900000.0   7900000.0   7700000.0  7.800000e+06  7.100000e+06   
4      7500000.0   7500000.0   6800000.0  8.000000e+06  7.000000e+06   
5      4200000.0   4200000.0   4800000.0  4.360000e+06  4.700000e+06   
6      4800000.0   4200000.0   4800000.0  4.360000e+06  4.700000e+06   
7      3500000.0   3500000.0   2700000.0  2.480000e+06  3.100000e+06   
8      4850000.0   4850000.0   5200000.0  5.400000e+06  4.200000e+06   
9      4750000.0   4750000.0   8680000.0  4.500000e+06  4.350000e+06   
10     4150000.0   4150000.0   3650000.0  3.300000e+06  3.650000e+06   
11     6980000.0   6980000.0   6450000.0  7.200000e+06  6.900000e+06   
12    13380000.0  13380000.0  11000000.0  1.480000e+07  1.314000

In [5]:
#print(type(data.index),data.index),range of index
#data是dataFrame格式的数据，而处理卷积的数据要求格式为np.narry,因此需要把数据转换出来，有没有更好的方法暂时没找
data_features=[] #特征数组
data_lables=[] #特征对应的标签


#data.iloc[i]=<class 'pandas.core.series.Series'> 取dataFrame行数据

for i in data.index:
    data_features.append([])  #为了形成二维数组[[],[],[]...]
    for index,v in data.iloc[i].items():
        if(index=='price_real'):
            data_lables.append(v)  
        else:
            data_features[i].append(v)
#print(data_features,data_lables)

In [6]:
#两种方式进行归一化，第一种用sklearn自带方法，是根据每个元素值在平均数的浮动来进行归一化，由于此种卷积出来的效果不好舍弃了
#第二种直接除以1kw
#scaler = preprocessing.StandardScaler()
# data_features=scaler.fit_transform(data_features)
# data_lables=scaler.fit_transform(data_lables)
data_features=np.array(data_features)/10000000
data_lables=np.array(data_lables)/10000000
print(data_features)


[[0.179   0.179   0.179   ... 0.179   0.179   0.179  ]
 [0.308   0.308   0.308   ... 0.308   0.308   0.308  ]
 [0.41    0.47    0.48    ... 0.553   0.553   0.553  ]
 ...
 [0.22    0.28    0.32    ... 0.285   0.285   0.285  ]
 [0.96    0.79    0.65    ... 0.78275 0.78275 0.78275]
 [0.81    0.81    0.81    ... 0.81    0.81    0.81   ]]


In [7]:
#处理原始数据
data_obj={
    b'data':data_features,
    b'lables':data_lables
}
print(data_obj)

{b'data': array([[0.179  , 0.179  , 0.179  , ..., 0.179  , 0.179  , 0.179  ],
       [0.308  , 0.308  , 0.308  , ..., 0.308  , 0.308  , 0.308  ],
       [0.41   , 0.47   , 0.48   , ..., 0.553  , 0.553  , 0.553  ],
       ...,
       [0.22   , 0.28   , 0.32   , ..., 0.285  , 0.285  , 0.285  ],
       [0.96   , 0.79   , 0.65   , ..., 0.78275, 0.78275, 0.78275],
       [0.81   , 0.81   , 0.81   , ..., 0.81   , 0.81   , 0.81   ]]), b'lables': array([0.179, 0.308, 0.41 , ..., 0.32 , 0.665, 0.81 ])}


In [8]:
# 定义数据格式 4*4*1，np.zeros创建空矩阵

blank_image= np.zeros((len(data_obj[b'data']),4,4,1), np.float64) 
print(blank_image)

[[[[0.]
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   [0.]]]


 ...


 [[[0.]
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   [0.]]]]


In [9]:
#向空矩阵中填充数据
#print(np.array(data_obj[b'data'][1][0:16]).reshape(4,4))
#print(blank_image[1][0:1,0:1,0:1])
# print(blank_image[1][0:2,0:2])
# print(blank_image[1][0:2,0:2,0])
#串联所有通道为一维数组，blank_image[i][:,:,0]，取第1个通道的全部值

for i in range(len(data_obj[b'data'])):
    blank_image[i][:,:,0]=np.array(data_obj[b'data'][i][0:16]).reshape(4,4)
    

In [10]:
data_obj[b'lables']=np.array(data_obj[b'lables'])
print(data_obj)

{b'data': array([[0.179  , 0.179  , 0.179  , ..., 0.179  , 0.179  , 0.179  ],
       [0.308  , 0.308  , 0.308  , ..., 0.308  , 0.308  , 0.308  ],
       [0.41   , 0.47   , 0.48   , ..., 0.553  , 0.553  , 0.553  ],
       ...,
       [0.22   , 0.28   , 0.32   , ..., 0.285  , 0.285  , 0.285  ],
       [0.96   , 0.79   , 0.65   , ..., 0.78275, 0.78275, 0.78275],
       [0.81   , 0.81   , 0.81   , ..., 0.81   , 0.81   , 0.81   ]]), b'lables': array([0.179, 0.308, 0.41 , ..., 0.32 , 0.665, 0.81 ])}


In [11]:
#划分训练测试集
X_train=blank_image[:2100]
X_test=blank_image[2100:]
y_train=data_obj[b'lables'][:2100]
y_test=data_obj[b'lables'][2100:]
print(len(X_train))
print(len(X_test))
print(len(y_train))
print(len(y_test))


2100
1901
2100
1901


In [12]:
# Make sure images have shape (28, 28, 1)
x_train = np.expand_dims(X_train, -1)
x_test = np.expand_dims(X_test, -1)


In [13]:
print("X_train shape:", X_train.shape)
print(X_train.shape[0], "train samples")
print(X_test.shape[0], "test samples")


X_train shape: (2100, 4, 4, 1)
2100 train samples
1901 test samples


In [14]:
input_shape = (4, 4, 1)
model = keras.Sequential(
    [
        keras.Input(shape=input_shape),
        layers.Conv2D(16, kernel_size=(3, 3),padding='same', activation="relu"),
        #layers.MaxPooling2D(pool_size=(2, 2)),
        layers.Conv2D(4, kernel_size=(3, 3),padding='same', activation="relu"),
        #layers.MaxPooling2D(pool_size=(2, 2)),
        layers.Conv2D(1, kernel_size=(3, 3),padding='same', activation="relu"),
        layers.Flatten(),
        #layers.Dropout(0.5),#避免过拟合
        layers.Dense(1,activation='linear')
    ]
)

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 4, 4, 16)          160       
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 4, 4, 4)           580       
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 4, 4, 1)           37        
_________________________________________________________________
flatten (Flatten)            (None, 16)                0         
_________________________________________________________________
dense (Dense)                (None, 1)                 17        
Total params: 794
Trainable params: 794
Non-trainable params: 0
_________________________________________________________________


In [16]:
import tensorflow as tf
tf.keras.losses.MeanSquaredError(reduction="auto", name="mean_squared_error")

model.compile(loss="mean_squared_error", optimizer="sgd", metrics=["accuracy"])

model.fit(X_train, y_train, batch_size=64, epochs=1,verbose=1, validation_split=0.1)

30/30 [==============================] - 0s 10ms/step - loss: 0.2127 - accuracy: 0.0000e+00 - val_loss: 0.2695 - val_accuracy: 0.0000e+00


In [17]:
score = model.evaluate(X_test, y_test, verbose=0)
print("Test loss:", score[0])
print("Test accuracy:", score[1])

Test loss: 0.09544708579778671
Test accuracy: 0.0


In [18]:
print(model.predict(X_test))

[[0.29504576]
 [0.35537782]
 [0.365847  ]
 ...
 [0.27740356]
 [0.31962666]
 [0.36283135]]


In [19]:
print(y_test)

[0.52  0.6   0.59  ... 0.32  0.665 0.81 ]


In [20]:
outputs = [layer.output for layer in model.layers] 

In [21]:
print(outputs)

[<tf.Tensor 'conv2d/Relu:0' shape=(None, 4, 4, 16) dtype=float32>, <tf.Tensor 'conv2d_1/Relu:0' shape=(None, 4, 4, 4) dtype=float32>, <tf.Tensor 'conv2d_2/Relu:0' shape=(None, 4, 4, 1) dtype=float32>, <tf.Tensor 'flatten/Reshape:0' shape=(None, 16) dtype=float32>, <tf.Tensor 'dense/BiasAdd:0' shape=(None, 1) dtype=float32>]


In [22]:
model.get_layer('conv2d_2')

In [23]:
#此处为了获得纯卷积结果，但是这个卷积是不纯的，因为经过了很多次迭代，不是一次卷积的结果，但是考虑到精确度不足4%，忽略了，换成一次迭代也是一样：（
#这个设计有点意思，把model拿过来再做一次，只为了得到某一层的卷积结果
layer_model =tf.keras.Model(inputs=model.input, outputs=model.layers[4].output)


In [24]:
#获得全部输入的卷积结果
feature=layer_model.predict(blank_image)

In [25]:
from sklearn import preprocessing

print(type(feature))
print(len(feature))

#此处解释了之前归一化为什么不用fit_transform，因为卷积结果还要还原
feature=feature*10000000
print(feature)

#再进行归一化，因为用XGboost方法训练的时候是用fit_transform归一化的
scaler = preprocessing.StandardScaler()
feature=scaler.fit_transform(feature)


#numpy.ndarray转换array，再利用array转换成dataFrame，存在.csv文件，是在愚钝只能用此蠢方法了
data=[]
for i in range(len(feature)):
    data.append([])
    data[i].append(feature[i][0])
#print(data)
dff=pd.DataFrame()
dd=dff.append(data)
dd.to_csv('round_price_predict.csv',index=False)

 



<class 'numpy.ndarray'>
4001
[[2672139.108181  ]
 [2853549.12281036]
 [3450033.96272659]
 ...
 [2774035.63261032]
 [3196266.59154892]
 [3628313.54141235]]


In [77]:
#另外一种方法获得卷积结果，殊途同归

from keras import backend as K
def get_output_function(model,output_layer_index):
    vector_funcrion=K.function([model.layers[0].input],[model.layers[output_layer_index].output])

    def inner(input_data):

        vector=vector_funcrion([input_data])[0]

        return vector
    return inner

In [78]:
get_feature=get_output_function(model,4)

In [79]:
feature=get_feature(X_test)

In [80]:
print(feature)

[[0.5141655 ]
 [0.47961882]
 [0.6933762 ]
 ...
 [0.27971557]
 [0.7742141 ]
 [0.81685627]]
